# Generated by Django 5.2.8 on 2026-06-26 07:27

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_id_alter_customerprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(default=1, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='habal/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='profile_picture',
            field=models.ImageField(default=1, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='habal/'),
            preserve_default=False,
        ),
    ]
