# Generated by Django 5.2.8 on 2026-06-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_customerprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
