# Generated by Django 5.2.8 on 2026-07-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_servicelocation_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelocation',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram Group Chat ID for this location.', max_length=50, null=True),
        ),
    ]
