# Generated by Django 5.2.8 on 2026-07-11 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_servicelocation_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='priority_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_bookings', to='booking.driverprofile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='priority_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
