# Generated by Django 5.2.8 on 2026-07-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_errand_type_booking_item_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_status', models.CharField(choices=[('active', 'Active'), ('no_rider', 'No Available Rider'), ('closed', 'Site is Closed Today, Opens Tomorrow'), ('under_repair', 'Under Repair')], default='active', max_length=30)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
