# Generated by Django 5.2.8 on 2026-07-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
